math_solver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('math_solver_app.urls'))
]

math_solver_app/urls.py
# Import some packages needed
from django.contrib import admin
from django.urls import path, include
from . import views

# Define app name and url patterns
app_name = 'math_solver_app'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('scanning-problem', views.upload_image, name = 'upload_image'),
    path('solving-problem', views.extract_problem, name = 'extract_problem'),
    path('solution', views.solve, name = 'solve')
]

math_solver_app/models.py
from django.db import models

# Create your models here.

math_solver_app/views.py
# Import django related tools
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

# Import other packages
from PIL import Image
from io import BytesIO
from firebase_admin import storage
import numpy as np
import cv2
import base64
import os
import random
import string
import json
import urllib

# Import core functions
from core.main import get_problem
from core.main import solve_problem

# Import parameter
from core.parameter import DELETE_PROCESSED_IMAGE

"""
Following function will create blob that connect to an image path in firebase
"""
def create_blob(file_path):
    # Connect to bucket
    bucket = storage.bucket()

    # Create blob
    blob = bucket.blob(file_path)
    return blob

# Following function will render main page of the apps
def index(request):
    return render(request, 'index.html')

"""
Following functions will handle the logic when user submit the problem through form
"""
# This first function will take the image and topic from user, and then send it to the server
def upload_image(request):
    try:
        # Get the input image
        problem_image = request.FILES['problem_image'].read()
        problem_image = base64.b64encode(problem_image)
        problem_image = Image.open(BytesIO(base64.b64decode(problem_image)))

        # Get the size of inputted image
        width, height = problem_image.size

        # Resize inputted image
        max_long = 300
        new_width = 0
        new_height = 0
        if width > height:
            new_width = max_long
            new_height = (height * max_long) // width
        else:
            new_height = max_long
            new_width = (width * max_long) // height
        problem_image = problem_image.resize((new_width, new_height))

        # Save as byte array
        img_byte_arr = BytesIO()
        problem_image.save(img_byte_arr, format = 'PNG')
        img_byte_arr = img_byte_arr.getvalue()

        # Generate random 16-digit string for image name
        image_name = ''.join(random.choice(string.ascii_lowercase) for count in range(16))

        # Create blob to upload the image to firebase
        blob = create_blob('problem/' + image_name)
        blob.upload_from_string(img_byte_arr)

        # Get public URL for that image
        blob.make_public()
        image_url = blob.public_url

        # Render problem detection loading page
        container = {
            'image_url': image_url,
            'image_name': image_name,
            'topic_field': request.POST['topic_field']
        }
        return render(request, 'problemDetectionLoading.html', container)
    except:
        # Prepare error message
        message = {
            'message': 'No Image Uploaded or File Not Supported'
        }

        # Render error page
        return render(request, 'error.html', message)

# This second function will scan the image to extract the problem
def extract_problem(request):
    try:
        # Get image name and the problem topic
        image_name = request.POST['image_name']
        topic = request.POST['topic_field']

        # Get the image from firebase
        blob = create_blob('problem/' + image_name)
        bytes_img = blob.download_as_bytes()
        problem_image = cv2.imdecode(np.frombuffer(bytes_img, np.uint8), -1)

        # Process the feature and get the features
        features, processed_image = get_problem(problem_image)

        # Save processed image as byte array
        _, encoded_image = cv2.imencode('.png', processed_image)
        encoded_bytes = encoded_image.tobytes()

        # Generate random 16-digit string for processed image name
        processed_image_name = ''.join(random.choice(string.ascii_lowercase) for count in range(16))

        # Save processed image to firebase
        blob = create_blob('problem/' + processed_image_name)
        blob.upload_from_string(encoded_bytes)

        # Get public URL for that processed image
        blob.make_public()

        # Turn dictionary features into string
        features_str = json.dumps(features)

        # Render solving problem loading page
        container = {
            'original_image_name': image_name,
            'processed_image_name': processed_image_name,
            'features_string': features_str,
            'topic': topic
        }
        return render(request, 'solvingProblemLoading.html', container)
    except:
        # Remove original image from firebase
        blob = create_blob('problem/' + image_name)
        blob.delete()

        # Prepare error message
        message = {
            'message': 'An Error Occured While Scanning The Problem'
        }

        # Render error page
        return render(request, 'error.html', message)

# This third function will solve the problem and return the result back to the user
def solve(request):
    try:
        # Get features, image name (both processed and original image) and topic
        features_string = request.POST['features_string']
        original_image_name = request.POST['original_image_name']
        processed_image_name = request.POST['processed_image_name']
        topic = request.POST['topic']

        # Get the processed image from firebase
        req = urllib.request.urlopen('https://storage.googleapis.com/math-solver-app.appspot.com/problem/' + processed_image_name)
        arr = np.asarray(bytearray(req.read()), dtype = np.uint8)
        image = cv2.imdecode(arr, -1)

        # Turn back string features into dictionary format
        features = json.loads(features_string)

        # Solve the problem
        qna_dict = solve_problem(image, features, topic)

        # Remove the image (both original and processed image)
        blob = create_blob('problem/' + original_image_name)
        blob.delete()
        if DELETE_PROCESSED_IMAGE:
            blob = create_blob('problem/' + processed_image_name)
            blob.delete()

        # Render solution page
        return render(request, 'solution.html', qna_dict)
    except:
        # Remove the image (both original and processed image)
        blob = create_blob('problem/' + original_image_name)
        blob.delete()
        if DELETE_PROCESSED_IMAGE:
            blob = create_blob('problem/' + processed_image_name)
            blob.delete()

        # Prepare error message
        message = {
            'message': 'An Error Occured While Solving The Problem'
        }

        # Render error page
        return render(request, 'error.html', message)

math_solver_app/templates/error.html
<!--
  Following HTML will be base template for all error type page
-->
<!DOCTYPE html>

<html>
  <head>
    <title>Math Solver</title>

    {% load static %}
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 col-lg-2"></div>

        <!-- This will be the content of each error page -->
        <div class="col-12 col-lg-8 error-page-main-container">
          <h1 class="error-page-oops-title">Oops!</h1>
          <h1 class="error-page-error-message">{{ message }}</h1>
          <img src="{% static 'images/sad.png' %}" class="error-page-symbol" alt="Error"/>
          <form method="POST" action="{% url 'math_solver_app:index' %}">
            {% csrf_token %}
            <div class="error-page-button-container">
              <button class="btn-lg btn-primary error-page-back-button" type="submit">Main Menu</button>
            </div>
          </form>
        </div>

        <div class="col-12 col-lg-2"></div>
      </div>
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

math_solver_app/templates/index.html
<!--
  Following HTML contains the view of starting page of the apps
-->
<html>
  <head>
    <title>Math Solver</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 col-lg-2"></div>

        <!-- Main Part of Starting Page -->
        <div class="col-12 col-lg-8 starting-page-main-div">
          <h1 class="starting-page-title">Math Solver</h1>

          <!-- Form Choose Topic -->
          <form method="POST" action="{% url 'math_solver_app:upload_image' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group starting-page-form-container">
              <div class="starting-page-topic-label">Select Topic</div>
              <select class="form-control-lg starting-page-input-topic" name="topic_field">
                <option value="simple_equation">Simple Equation</option>
              </select><br />
              <div class="starting-page-problem-image-label">Problem Image</div>
              <input type="file" accept="image/*" name="problem_image" class="starting-page-choose-problem">
              <br /><button id="solveNowButton" onclick="loadingMessage()" type="submit" class="btn-lg btn-primary starting-page-solve-button">Solve Now!</button>
              <div id="loadingMessage" class="starting-page-loading-message">
                Uploading Image, Please Wait 
                <span class="loading-point-1">.</span>
                <span class="loading-point-2">.</span>
                <span class="loading-point-3">.</span>
              </div>
            </div>
          </form>

          <h3 class="starting-page-created-by">Created By : Garry Ariel</h3>
        </div>
        
        <div class="col-12 col-lg-2"></div>
      </div>
    </div>

    <!-- Javascript Code -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
      // Following function will activate loading message when user click on Solve Now button
      loadingMessage = () => {
        // Remove Solve Now button
        document.getElementById('solveNowButton').style.display = "none";

        // Display loading message
        document.getElementById('loadingMessage').style.display = "block";
      }
    </script>

  </body>
</html>

math_solver_app/templates/problemDetectionLoading.html
<!--
  Following HTML contains the view of starting page of the apps
-->
<html>
  <head>
    <title>Math Solver</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 col-lg-2"></div>

        <!-- Main Part of Problem Detection Loading Page -->
        <div class="col-12 col-lg-8 problem-detect-page-main-div">
          <h1 class="problem-detect-page-title">Image Uploaded!</h1>
          <div class="container-fluid">
            <div class="row">
              <div class="col-3"></div>
              <div class="problem-detect-page-problem-image-container col-6">
                <img class="problem-detect-page-problem-image" src="{{ image_url }}" alt="Problem Image" />
                <div class="problem-detect-page-scanner"></div>
              </div>
              <div class="col-3"></div>
            </div>
          </div>
          <h1 class="problem-detect-page-message-1">Now Scanning The Problem</h1>
          <h1 class="problem-detect-page-message-2">Please Wait</h1>

          <!-- Hidden element to trigger next loading screen  -->
          <form method="POST" action="{% url 'math_solver_app:extract_problem' %}">
            {% csrf_token %}
            <input type="text" name="image_name" value="{{ image_name }}" class="problem-detect-page-hidden-input" />
            <input type="text" name="topic_field" value="{{ topic_field }}" class="problem-detect-page-hidden-input" />
            <br /><button id="nextScreenButton" type="submit" class="btn-lg btn-primary problem-detect-page-hidden-button"></button>
          </form>

        </div>
        
        <div class="col-12 col-lg-2"></div>
      </div>
    </div>

    <!-- Javascript Code -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
      // Trigger next loading screen event when the page has been loaded
      window.onload = function() {
          // Get activation button
          var submitBtn = document.getElementById('nextScreenButton');

          // Click on the button
          submitBtn.click();
      };
    </script>

  </body>
</html>

math_solver_app/templates/solution.html
<!--
  Following HTML contains the view of solution page (the question, explanation and answer will be displayed)
-->
<html>
  <head>
    <title>Math Solver</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 col-lg-2"></div>

        <!-- Main Part of Solution Page -->
        <div class="col-12 col-lg-8 solution-page-main-div">
          <h1 class="solution-page-question-title">Question</h1>
          <h2 class="solution-page-question-content">{{ question }}</h2>
          <h1 class="solution-page-answer-title">Answer</h1>
          <h2 class="solution-page-answer-content">{{ answer }}</h2>
          <form method="POST" action="{% url 'math_solver_app:index' %}">
            {% csrf_token %}
            <div class="solution-page-button-container">
              <button class="btn-lg btn-primary solution-page-back-button" type="submit">Main Menu</button>
            </div>
          </form>
        </div>
        
        <div class="col-12 col-lg-2"></div>
      </div>
    </div>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

math_solver_app/templates/solvingProblemLoading.html
<!--
  Following HTML contains the view of starting page of the apps
-->
<html>
  <head>
    <title>Math Solver</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 col-lg-2"></div>

        <!-- Main Part of Solving Problem Page -->
        <div class="col-12 col-lg-8 solve-problem-page-main-div">
          <h1 class="solve-problem-page-title">We Have Got Your Problem!</h1>
          <img class="solve-problem-page-loading" src="{% static 'images/loading.gif' %}" alt="Solving Your Problem" />
          <h1 class="solve-problem-page-message-1">Now Solving The Problem</h1>
          <h1 class="solve-problem-page-message-2">Please Wait</h1>

          <!-- Hidden element to trigger next loading screen  -->
          <form method="POST" action="{% url 'math_solver_app:solve' %}">
            {% csrf_token %}
            <input type="text" name="original_image_name" value="{{ original_image_name }}" class="solve-problem-page-hidden-input" />
            <input type="text" name="features_string" value="{{ features_string }}" class="solve-problem-page-hidden-input" />
            <input type="text" name="processed_image_name" value="{{ processed_image_name }}" class="solve-problem-page-hidden-input" />
            <input type="text" name="topic" value="{{ topic }}" class="solve-problem-page-hidden-input" />
            <br /><button id="nextScreenButton" type="submit" class="btn-lg btn-primary solve-problem-page-hidden-button"></button>
          </form>
        </div>
        
        <div class="col-12 col-lg-2"></div>
      </div>
    </div>

    <!-- Javascript Code -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script>
      // Trigger next screen event when the page has been loaded
      window.onload = function() {
          // Get activation button
          var submitBtn = document.getElementById('nextScreenButton');

          // Click on the button
          submitBtn.click();
      };
    </script>

  </body>
</html>